# Generated by Django 5.2.7 on 2025-10-26 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule', models.JSONField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
            ],
            options={
                'db_table': 'composite_rules',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='composite_r_is_acti_4edcc2_idx'), models.Index(fields=['is_active', 'created_at', 'id'], name='composite_r_is_acti_ab7b94_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('threshold', models.FloatField(default=0.8)),
                ('model_name', models.CharField(default='ModSpecialization/distilbert-base-uncased-fraud-classifer', max_length=200)),
                ('input_template', models.TextField(default='Transaction {transaction_type} amount {amount} from {sender_account} to {receiver_account} at {timestamp} location {location}', help_text='Шаблон для преобразования транзакции в текст')),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
            ],
            options={
                'verbose_name': 'ML правило',
                'verbose_name_plural': 'ML правила',
                'db_table': 'ml_rules',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='ml_rules_is_acti_6b0f7e_idx'), models.Index(fields=['is_active', 'created_at', 'id'], name='ml_rules_is_acti_df3008_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatternRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('window_seconds', models.PositiveIntegerField(default=600)),
                ('min_count', models.PositiveIntegerField(default=3)),
                ('total_amount_limit', models.FloatField(blank=True, null=True)),
                ('min_amount_limit', models.FloatField(blank=True, null=True)),
                ('group_mode', models.CharField(choices=[('sender', 'Только отправитель'), ('receiver', 'Только получатель'), ('pair', 'Пара отправитель–получатель')], default='sender', max_length=20)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
            ],
            options={
                'verbose_name': 'Паттерновое правило',
                'verbose_name_plural': 'Паттерновые правила',
                'db_table': 'pattern_rules',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='pattern_rul_is_acti_214e22_idx'), models.Index(fields=['is_active', 'created_at', 'id'], name='pattern_rul_is_acti_883250_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('column_name', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=5)),
                ('value', models.FloatField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
            ],
            options={
                'db_table': 'threshold_rules',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='threshold_r_is_acti_afcfe3_idx'), models.Index(fields=['is_active', 'created_at', 'id'], name='threshold_r_is_acti_26f465_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sender_account', models.CharField(db_index=True, max_length=32)),
                ('receiver_account', models.CharField(db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(blank=True, max_length=30, null=True)),
                ('merchant_category', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('device_used', models.CharField(blank=True, max_length=20, null=True)),
                ('time_since_last_transaction', models.FloatField(blank=True, null=True)),
                ('spending_deviation_score', models.FloatField(blank=True, null=True)),
                ('velocity_score', models.FloatField(blank=True, null=True)),
                ('geo_anomaly_score', models.FloatField(blank=True, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_fraud', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('processed', 'Processed'), ('alerted', 'Alerted')], db_index=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['status', 'is_reviewed'], name='transaction_status_8aa4c9_idx'), models.Index(fields=['sender_account', 'receiver_account'], name='transaction_sender__ab116a_idx'), models.Index(fields=['correlation_id', 'timestamp'], name='transaction_correla_c04b86_idx')],
            },
        ),
    ]
